version: "2.3"

services:
    static_server:
        image: ghcr.io/userver-framework/docker-userver-build-base:v1
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/static_server/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
        volumes:
          - .:/static_server:rw
          - ./third_party/userver/tools/docker:/tools:ro
        ports:
          - 8080:8080
        working_dir: /static_server
        entrypoint:
          - /tools/run_as_user.sh
